### PR TITLE
Fix  typo

### PR DESCRIPTION
**Pull request by mesqueeb**
## 🎁 Pull Request

* [x] Used a clear / meaningful title for this pull request
* [ ] Tested the changes in your own code (on your projects)
* [ ] Added / Edited tests to reflect changes (`tst` folder)
* [ ] Have read the **Contributing** part of the **Readme**
* [ ] Passed `npm test`

#### Fixes

just a typo

#### What changes have you made?
fix the typo

#### What tests have you updated?
none

#### Is there any breaking changes?
no

### CODE REVIEW

**Comment by mesqueeb** [comment]
@millsp hey, I didn't think following the complex contribution guide was necessary to just fix a typo in the docs/JSDocs, but I'm not sure. I just thought I'd open the PR and see what will happen. :D feel free to close if you don't like it because I didn't follow all the contribution guide lines!!

**Comment by millsp** [comment]
Thank you so much, will merge soon

**Comment by millsp** [comment]
I will merge this in the upcoming version `9`. Thanks!

**Comment by millsp** [comment]
Merged! Thank you :)

**Comment by mesqueeb** [comment]
@millsp really?? Says unmerged to me :P

**Comment by millsp** [comment]
It's on my local next branch. Preparing for ts-toolbelt 9! Lots of cleaning, simplifying, optimizing, removing, & string utilities!

**Pull request closed without merging**
