### PR TITLE
Add Object/Members type to extract the list of member types of any object

### PR DESCRIPTION
**Pull request by Methrat0n**
## 🎁 Pull Request

* [x] Used a clear / meaningful title for this pull request
* [x] Tested the changes in your own code (on your projects)
* [x] Added / Edited tests to reflect changes (`tst` folder)
* [x] Have read the **Contributing** part of the **Readme**
* [x] Passed `npm test`

#### Fixes

There is no issue with this as the contributing section does not ask to create one first.

#### Why have you made changes?

I used ts-toolbet to create this type and use it in my library [ts-match](https://github.com/Methrat0n/ts-match).
I think it can be of use to others and want to give back to this project which helps a lot in my work.

#### What changes have you made?
* Add Members.ts file in the Object directory
* Add export of the Members type in the Object/_api.ts

#### What tests have you updated?
* Add test for Members

#### Is there any breaking changes?

* [ ] Yes, I changed the public API & documented it
* [ ] Yes, I changed existing tests
* [x] No,  I added to the public API & documented it
* [ ] No,  I added to the existing tests
* [ ] I don't know

#### Anything else worth mentioning?

I commented one test which was failing and intends to create an issue about it.
I will gladly uncomment it if you prefer.

### CODE REVIEW

**Comment by millsp** [comment]
Hey @Methrat0n, thanks for the proposition :)

I will not merge this, but thanks for your nice intentions. I appreciate.

```ts
type equivalent = TupleOf<UnionOf<YOUR OBJECT>>
```

**Comment by Methrat0n** [comment]
I respect your choice, but I want to point out that your solution is not equivalent: you lose the types that are present multiple times. My second example with 2 number would not give the same result as yours.

**Comment by millsp** [comment]
Does this work four you?

```ts
type Members<O extends object> =
    U.ListOf<keyof O> extends infer LK
    ? {[K in keyof LK]: O.At<O, LK[K] & keyof O>}
    : never

type test0 = Members<{a: 1, b: 2, c: {a: 1}}>
```

**Comment by Methrat0n** [comment]
Yes, it does and thank's for the better implementation. That way of iterating over an array is really neet.

**Pull request closed without merging**
